### ISSUE TITLE
Craft Commerce 

### ISSUE THREAD

**Issue by damiengahan** [craftcms/webhooks#11]
Thanks for this plugin, it's really helpful!
I'm using it to pull new order info from Commerce using craft\commerce\elements\Order as the sender class on afterCompleteOrder.
This all works great but I've been having trouble working out how to pull in further order data from Commerce like "totalTax". 
Just wondering if this is possible?
Also is it possible to bring in custom product/user fields?

Appreciate any help you can give!

**Comment by brandonkelly** [comment]
The data available will depend on what attributes the event sender’s class makes available. In the case of `craft\commerce\elements\Order`, `totalTax` is in fact available, as it is defined in `extraAttributes()`:

https://github.com/craftcms/commerce/blob/06dcec2ddd364176071fcb9afb777f42a5db06a1/src/elements/Order.php#L1200

**Comment by kaspar-allenbach** [comment]
I'm trying to use the webhook plugin for orders as well on `craft\commerce\elements\Order` but I don't understand how to get the order data of the current order:

```

{% set order = event.sender %}

{
  "data": [
    {
      "event_name": "checkout",
      "event_time": {{ order.dateOrdered | date('U') }},
      "event_id": "{{ order.reference }}",
       // blabla
```

This doesn't work.

Shouldn't `event.sender` contain craft commerce order data?
