### ISSUE TITLE
[FR] Ability to attach arbitrary headers for each webhook

### ISSUE THREAD

**Issue by pauloelias** [craftcms/webhooks#12]
We have a situation where we need to send requests to an API that requires specific headers for authentication in order to perform certain tasks. Adding the ability to define arbitrary headers along with each webhook would be amazing!

Eventually being able to define headers per environment in the config file would be 🔥 🔥 🔥

**Comment by brandonkelly** [comment]
Just released Webhooks 2.2.0 with this!

<img width="696" alt="Screen Shot 2019-07-29 at 6 33 34 AM" src="https://user-images.githubusercontent.com/47792/62053529-aa4b0a00-b1cc-11e9-8df5-5c498610f0dd.png">

https://github.com/craftcms/webhooks#sending-custom-headers

**Comment by pauloelias** [comment]
This is awesome, thank you @brandonkelly!
