### ISSUE TITLE
3.2 Beta Fires Sooooo Many saveEntry Events

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/webhooks#13]
Will there be some way to limit this behavior when it comes to the Webhooks plug-in. Maybe a new event... or perhaps you really do need to revisit conditionals in the settings of the plug-in. I am testing and it fired 13 Webhooks in 90 seconds - so I am assuming each auto save is sending a separate hook. Thanks!

If this is better off in Craft repo let me know.

<img width="1323" alt="Screen Shot 2019-06-07 at 11 17 05 AM" src="https://user-images.githubusercontent.com/8887839/59118508-f9379a00-8915-11e9-9975-af8bc3db12e9.png">

**Comment by minyangu-bgl** [comment]
I have the same issue here, majority events are generated by the autosave feature introduced in 3.2.

They have recently disabled the auto-creation of draft in Craft CMS when editing an Entry. However, when you create a new Entry, it auto creates a draft, and hence the auto-saving is still enabled. I'm not sure how they decide the saving-points, but it feels like they are firing multiple events per saving-point when you hit the Save button.

I think the solution is either to raise a FR ticket inside Craft CMS to let end user to disable the autosaving feature completely, or raise a FR ticket here to enhance the webhook so it can filter out the event based on object status, e.g. isDraft, isRevision etc..

**Comment by brandonkelly** [comment]
We just released Webhooks 2.1.0 with a new Event Filters feature, which lets you prevent the webhook from executing in certain conditions:

<img width="414" alt="Event Filters" src="https://user-images.githubusercontent.com/47792/61983987-56b3a300-afb7-11e9-92d8-bc26d4d6b1af.png">

This will drastically reduce the number of webhooks that get sent.
