### ISSUE TITLE
[FR] Ability to filter event based on object status

### ISSUE THREAD

**Issue by minyangu-bgl** [craftcms/webhooks#14]
Craft 3.2 autosave fires many events and majority of them I don't care at webhook level, since these events are generated from Draft/Revision objects.

It will be good to add a filter option on event's entry fields, e.g. isNew, isDraft, isRevision
For our use case, we only want the webhook make a request when the entry contains below field values:
```
"isDraft": false
"isRevision": false
```
@brandonkelly

**Comment by brandonkelly** [comment]
We just released Webhooks 2.1.0 with this:

<img width="414" alt="Event Filters" src="https://user-images.githubusercontent.com/47792/61983987-56b3a300-afb7-11e9-92d8-bc26d4d6b1af.png">

**Comment by minyangu-bgl** [comment]
This is PERFECT!! Thank you Brandon for quickly adding this new feature to resolve our issue with craft 3.2 autosave, much appreciated!

**Comment by isjackwild** [comment]
This is super useful! However — what does the dot in the middle mean? I understand the tick and the cross but the dot is a bit of a mystery ;)
