### ISSUE TITLE
Failed webhooks blocks the queue forever

### ISSUE THREAD

**Issue by jaypeng2015** [craftcms/webhooks#15]
Craft Version: 3.2.6 Pro
Database: posgresql 11.4
Plugin version: 2.0.1
Runtime: PHP 7.2 running on 64bit Amazon Linux/2.8.12
No warnings under CMS System Report.
Sender Class: craft\elements\Entry
Event: afterSave

The UI shows the status after saving an entry:
![image](https://user-images.githubusercontent.com/14153855/61838863-9c487100-aece-11e9-91ab-da94d266eff7.png)

This was because the webhook endpoint is unavailable.

webhooks.php:
```
<?php
return [
  'maxDepth' => 10,
  'maxAttempts' => 3,
  'attemptDelay' => 120,
];
```

However this doesn't stop after 3 (or 4) attempts, instead it clears `dateReserved` and `timeUpdated` and keeps running.

- The event was created on 24th July

- On 25th July
![image](https://user-images.githubusercontent.com/14153855/61839089-91daa700-aecf-11e9-951b-e3228d7ada92.png)

- A few minutes later, after creating a new entry, it updates `dateReserved` and `timeUpdated` of the first record in the queue.
![image](https://user-images.githubusercontent.com/14153855/61839464-f813f980-aed0-11e9-8193-23c8ff0bb291.png)

- 10 min later, it clears the value again
![image](https://user-images.githubusercontent.com/14153855/61839841-72914900-aed2-11e9-85cc-7d1c8bf8623a.png)

- Remains the same after 1 hour if no new events. But as long as a new `afterSave` event gets triggered, it updates  `dateReserved` and `timeUpdated` of the first record in the queue and increase numbers of attempts by 1.

Appreciate any help!

**Comment by minyangu-bgl** [comment]
Maybe this could help you as a workaround?
https://github.com/lukeyouell/craft-queue-manager

**Comment by jaypeng2015** [comment]
Thanks @minyangu-bgl, the plugin may help us from a developer's prospective, but not for commercial users I think.

**Comment by jaypeng2015** [comment]
@minyangu-bgl tried craft-queue-manager, but it doesn't work for some reason if the queue is not empty.
![image](https://user-images.githubusercontent.com/14153855/61922398-a2f4e800-afa3-11e9-867b-ab5a79f8f251.png)

**Comment by jaypeng2015** [comment]
More information about the bug itself is that the activity tab always shows pending and there's no attempts. So it's more likely that the job is not triggered at all.

Works on localhost through.

![image](https://user-images.githubusercontent.com/14153855/61922528-24e51100-afa4-11e9-8ccb-ce3249ea7095.png)

**Comment by jaypeng2015** [comment]
It turns out that the root cause of this is this issue: https://github.com/craftcms/cms/issues/2715

After I applied the sql `ALTER DATABASE dbname SET bytea_output TO 'escape';`, everything started to work now.
