### ISSUE TITLE
[3.2 ] Scheduled events

### ISSUE THREAD

**Issue by jaypeng2015** [craftcms/webhooks#17]
Craft Version: 3.2.6 Pro
Plugin version: 2.1.0

Our use case is using webhooks to trigger another service to call element-api (https://github.com/craftcms/element-api) to get all the entries, and it works well for afterSave/afterDelete/afterRestore on entries.

However when adding `Post Date` and `Expiry Date` to the entry,  webhooks triggers immediately after save, but it doesn't trigger new events when the time comes to `Post Date` and `Expiry Date`, or maybe it does trigger but maybe some event that I do not know.

Can someone please help?

**Comment by brandonkelly** [comment]
Unfortunately there isn't a great solution to this yet. For Craft 4, we want to get all entry publishing/expiring to happen via a job scheduler that runs every minute, at which point we could introduce new events that trigger right when an entry goes live, and right when an entry expires.

**Comment by tomascordero** [comment]
@brandonkelly I know this is a pretty old convo but is there any event that fires now when a post's status is changed based on the Expiry Date? Same question for the Post Date. Im not seeing much in way of documentation for when these events would be fired off if they do get fired off at all.

**Comment by tomascordero** [comment]
@brandonkelly unfortunately I did end up getting an answer and the answer was that there's no mechanism that tells id something is expired or not. It calculates that when it calls the entry. So you'd have to set up a cron job or something to constantly check all posts and fire a webhook of the posts it found expired.

**Comment by reilnuud** [comment]
@brandonkelly sorry to dig this one up again, but is there any chance this is on the roadmap for Craft 5?

**Comment by brandonkelly** [comment]
@reilnuud Sorry, we haven’t had a chance to circle back on this yet.
