### ISSUE TITLE
Event inside payload only listing public property values

### ISSUE THREAD

**Issue by gustavs-gutmanis** [craftcms/webhooks#2]
As it is currently, only the `public` properties of the `Event` are added to the webhook's payload.  

What if we have `private` properties that are only exposed via getters and have setters that define how class properties should be altered? Not only is having properties `public` not a good practice, some events have special logic taking place which updates its properties in a given manner and thus they cannot be exposed. Otherwise, third party plugins capturing that event might corrupt the data and cause unexpected side-effects.  

Would you consider adding, for instance, a check that determines if the `Event` implements `\JsonSerializable` and then use its `::jsonSerialize()` instead of looking through exposed `public` properties? Or perhaps check for the presence of getter methods akin to [symfony/property-access](https://symfony.com/doc/current/components/property_access.html)?

**Comment by brandonkelly** [comment]
If your class implements the [yii\base\Arrayable](https://www.yiiframework.com/doc/api/2.0/yii-base-arrayable) interface, your [fields()](https://www.yiiframework.com/doc/api/2.0/yii-base-arrayable#fields()-detail) method can list the getter-based properties, and they will be included when serializing the object.

Assuming your class extends a class that uses [yii\base\ArrayableTrait](https://www.yiiframework.com/doc/api/2.0/yii-base-arrayabletrait) (which is generally the case), it would look like this:

```php
public function fields()
{
    $fields = parent::fields();
    $fields[] = 'foo';
    $fields[] = 'bar';
    return $fields;
}
```

If you don’t want those properties to be included every time objects are converted to an array, you can override [extraFields()](https://www.yiiframework.com/doc/api/2.0/yii-base-arrayable#extraFields()-detail) instead, and then list the properties in the “Extra Sender Attributes” setting instead:

```
foo
bar
```

**Comment by gustavs-gutmanis** [comment]
Thanks for the help!

I'm probably doing something wrong, but implementing the `\yii\base\Arrayable` interface and it's methods - yield no results. The `::fields()` and `::toArray()` methods never even get called, and I assume that is because 

``` php
$eventAttributes = $webhook->getEventAttributes();
foreach ((new \ReflectionObject($e))->getProperties() as $property) {
    if ($property->isPublic() && $property->getDeclaringClass()->getName() !== Event::class) {
        $name = $property->getName();
        $data['event'][$name] = $this->toArray($e->$name, $eventAttributes[$name] ?? []);
    }
}
```

The part where data is appended to the payload - it checks for `$property->isPublic()`. Doesn't look like it implementing the `\yii\base\Arrayable` interface does the event any good, unfortunately.  

I tried both - using the `\yii\base\ArrayableTrait` and implementing the interface methods myself, and they're never called.

Any help would be appreciated.

**Comment by brandonkelly** [comment]
The easiest way to implement `yii\base\Arrayable` is to use `yii\base\ArrayableTrait`.

```php
use yii\base\ArrayableTrait;

class MyClass
{
    use ArrayableTrait;

    public function fields()
    {
        return [
            '...',
        ];
    }

    // ...
}
```

Your class may already be extending a class that uses the trait though, so make sure that’s not the case before adding it yourself.

The serialization logic happens in `craft\webhooks\Plugin::_toArray()`:

https://github.com/craftcms/webhooks/blob/33185bc033be91904d6e116ba86d6ed2f7f22cc7/src/Plugin.php#L115-L126

Line 18 there is where `toArray()` will be called if the class implements `yii\base\Arrayable`.

The code you quoted is for finding any event-specific properties defined by the event class (e.g. [craft\events\ElementEvent::$element](https://github.com/craftcms/cms/blob/master/src/events/ElementEvent.php#L27)). The plugin will serialize their values just like `$event->sender`, etc., via `Plugin::_toArray()`.
