### ISSUE TITLE
Error when SEOmatic is installed

### ISSUE THREAD

**Issue by edolyne** [craftcms/webhooks#20]
When SEOmatic is installed a 'An Error Has Occurred' message appears when attempting to add a new webhook, and the following error is logged:

`error - yii\base\ErrorException:64
yii\base\ErrorException: Cannot use 'False' as class name as it is reserved in /xxx/vendor/nystudio107/craft-seomatic/src/models/jsonld/False.php:24`

**Comment by jasonmccallister** [comment]
@edolyne this was resolved in this release of SEOMatic: https://github.com/nystudio107/craft-seomatic/releases/tag/3.2.33

**Comment by jasonmccallister** [comment]
@edolyne since this was resolved by the SEOMatic release I am going to close this issue. If this remains a problem, can you verify that you are up to date with SEOMatic?
