### ISSUE TITLE
FR: Allow PUT requests

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/webhooks#21]
I'd like to use this to update MailChimp contacts when users are updated, but it requires PUT and doesn't work with POST when the contact already exists.

Is that on the roadmap? Could it be?

**Comment by KatieMFritz** [comment]
https://github.com/craftcms/webhooks/pull/23 addresses this.

**Comment by brandonkelly** [comment]
Resolved via #23. Thanks again!

**Comment by brandonkelly** [comment]
2.3.0 is out now with that change.
