### ISSUE TITLE
Bug: disabling webhook deletes custom payload

### ISSUE THREAD

**Issue by KatieMFritz** [craftcms/webhooks#22]
## Steps to reproduce:

1. Create a working webhook with a custom payload
2. From the index view, disable the webhook
3. Re-enable the webhook

## Expected behavior:

All data would still be there.

## What actually happens:

The custom payload is wiped out.

**Comment by brandonkelly** [comment]
Thanks for reporting that! Just fixed for the next release.

**Comment by KatieMFritz** [comment]
Thanks! When is the next release planned?

**Comment by brandonkelly** [comment]
Just released 2.3.0 :)
