### ISSUE TITLE
Integrating webhooks with Gatsby Cloud

### ISSUE THREAD

**Issue by daniel-vc** [craftcms/webhooks#28]
Hi there! We've been trialing the plugin for use with our test build runner, Gatsby Cloud but have encountered the below problems.

1. After creating a new web hook in the CMS and creating a new news entry and hitting publish, it has worked as far as building in Gatsby Cloud, but after the first run it then no longer seems to work. (See attached images of the activity log and that of the entries in the CMS) 
2. Multiple build requests. See attached photo below of the multiple build requests sent from the plugin that Gatsby cloud cancels most and runs just one (rightly so). I've spoken to Gatsby Cloud and they say it's sending multiple requests from the plugin end, which haven looked at the activity log, it seems to send multiple for 1 publish. See attached screenshot of the web hook ‘scratch’ that has 7 posts when I only clicked publish once. Also, this only has the filter ‘Element is new’ applied (see attached photo of the web hook config). Again, to replicate the issue, this will only happen after the initial set up of a new web hook, each time.

## How to replicate the issue. 
1. Set up a gatsby project in your Github.  Fork the sample one i've set up [here](https://github.com/daniel-vc/project-loop-gatsby).
2. Setup a gatsby cloud account at [gatsbyjs.com](https://www.gatsbyjs.com) ignoring (at this setup prompt) the sections to add cms integrations and environment variables.
3. Have a test CraftCMS admin site handy with the plugin and graphql enabled with an endpoint setup
4. Add your Data endpoint token as a variable called `GATSBY_GRAPHQL_TOKEN` to the **Build Environment Variables** and **Preview Environment Variables** in the **site settings** -> **General** -> **Environment Variables** section.
5. Copy the builds Webhook token from the webhooks site setting section and paste into the set up of a new webhook in Craft. Set up the webhook with same settings as provided in the attached screenshot below and save.
6. With the webhook tokens setup in Craft CMS and Environment variables setup in Gatsby Cloud, try publishing a new article in craft and test the outcomes.

Any questions, feel free to give me a shout 👍 

--------------------------------------------------------------------------------------------
When plugin does send a request - get multiple build requests

<img width="1126" alt="Data builds when working" src="https://user-images.githubusercontent.com/39903900/79446618-63a97400-7fd6-11ea-902f-0147f6643178.png">
--------------------------------------------------------------------------------------------
Activity log shows 7 sent requests from 1 publish with webhook 'scratch'
<img width="1201" alt="Activity Log" src="https://user-images.githubusercontent.com/39903900/79446701-92bfe580-7fd6-11ea-8f75-a128e2f2bea4.png">

--------------------------------------------------------------------------------------------
To further show builds not working - these are Latest entries in CMS don't correspond to the output in my test page (see next screenshot)
<img width="1053" alt="Entries in CMS" src="https://user-images.githubusercontent.com/39903900/79446786-baaf4900-7fd6-11ea-9aaf-31ead672a31a.png">

--------------------------------------------------------------------------------------------
Current entries showing on the page. Latest entry should be 'Lets try today'
<img width="752" alt="Data" src="https://user-images.githubusercontent.com/39903900/79446837-d0247300-7fd6-11ea-8eb1-cd9020169ce1.png">

--------------------------------------------------------------------------------------------
Last built in Gatsby cloud which shows the plugin not receiving any requests for over 21hours despite sending multiple requests from the Craft plugin.
<img width="1123" alt="Last built" src="https://user-images.githubusercontent.com/39903900/79447011-17126880-7fd7-11ea-9f36-5738cf10a1ea.png">

--------------------------------------------------------------------------------------------
Webhook settings in the CMS
<img width="944" alt="Plugin Settings" src="https://user-images.githubusercontent.com/39903900/79447116-475a0700-7fd7-11ea-9b0a-b4f86421d90d.png">

**Comment by brandonkelly** [comment]
Do you have multiple sites? If so, how many?

**Comment by danielvanc** [comment]
It’s just for for 1 site

**Comment by daniel-vc** [comment]
It's just 1 example site at the moment.

**Comment by brandonkelly** [comment]
Can you send a database backup and your `composer.json` + `composer.lock` files over to support@craftcms.com, along with steps to reproduce?

**Comment by daniel-vc** [comment]
I provided the steps to re-produce in my original post...

Will send the files over now...

**Comment by daniel-vc** [comment]
Hey @brandonkelly, 

Just checking in to see if there's any update on this yet? Did send you an email but haven't heard anything back yet.


Thanks 👍

**Comment by brandonkelly** [comment]
@daniel-vc Sorry, been slammed. It’s still in my inbox and will get to it as soon as I can.

**Comment by brandonkelly** [comment]
We just released Webhooks 2.3.0, which adds a new [Debouncing](https://github.com/craftcms/webhooks#debouncing-webhooks) feature. I suspect it will help solve your issue.
