### ISSUE TITLE
Request Method & URL as an environment variable

### ISSUE THREAD

**Issue by jamiewade** [craftcms/webhooks#30]
I have added an environment variable to my `.env`:

`CLC_AFTER_ENTRY_DELETE="https://www.google.co.uk/"`

And when I use that variable in my Webhook settings, I get this error:

![screenshot](https://user-images.githubusercontent.com/6672331/80510820-28faf080-8973-11ea-984e-e530a6768a14.png)

> URL is not a valid URL.

What am I doing wrong?

Craft CMS 3.4.17.1
**Webhooks**: 2.2.0

**Comment by cjativa** [comment]
Hi I see this same error. 
![image](https://user-images.githubusercontent.com/41299115/81460726-32efd100-9175-11ea-8432-762a5bfe1f72.png)

**Comment by sjelfull** [comment]
+1. The documentation mention its possible, but its not released. You can install preview by checking out #18

**Comment by brandonkelly** [comment]
Yeah sorry, just changed the repo’s default branch to `master` so the readme only mentions shipped features. We’ll be releasing 2.3.0 soon with the new URL environment variable support.

**Comment by jamiewade** [comment]
Thanks Brandon!

**Comment by brandonkelly** [comment]
2.3.0 is out now with that feature.
