### ISSUE TITLE
[FR] Disable certificate checks on demand

### ISSUE THREAD

**Issue by sjelfull** [craftcms/webhooks#31]
When posting to a https-enabled Gatsby server with a self-signed certificate, I'm not able to trigger the refresh endpoint enabled by `ENABLE_GATSBY_REFRESH_ENDPOINT`.

Could you add a option to disable certificate checks (which is probably the cause here).

**Comment by brandonkelly** [comment]
I’ve just added a new `guzzleConfig` setting for the next release, which you can set from `config/webhooks.php` to tweak the Guzzle config used to send webhook requests:

```php
return [
    'guzzleConfig' => [
        'verify' => false,
    ],
];
```

**Comment by brandonkelly** [comment]
Webhooks 2.3.0 is out now with that change.
