### ISSUE TITLE
Failed webhook calls block further calls

### ISSUE THREAD

**Issue by joshuabaker** [craftcms/webhooks#35]
### Description

We’ve got a headless Craft install that triggers a build in Vercel. Due to our using a debounce key, if there’s an issue with a request the system gets stuck ‘Pending’ forever, with all subsequent requests dropped as they also match the debounce key.

![image](https://user-images.githubusercontent.com/160484/86364349-fa014380-bc6f-11ea-80cd-c7e6f34f8630.png)

### Steps to reproduce

Obviously hard to reproduce, however, simulating the pending state whilst using a debounce key might be possible.

### Additional info

- Craft version: Craft CMS 3.5.0-beta.3
- PHP version: 7.4.4
- Database driver & version: 5.7.26
- Plugins & versions:
    - Amazon S3: 1.2.8
    - Amazon SES: 1.3.1
    - AsyncQueue: 2.1.1
    - Control Panel CSS: 2.2.1
    - Copy: 1.0.0-RC11
    - Dashboard Begone: 1.0.1
    - Entry Instructions: 1.0.7
    - ImageOptimize: 1.6.14
    - Image Resizer: 2.0.9
    - oEmbed: 1.3.4
    - Redactor: 2.6.1
    - Scout: 2.3.1
    - SEO: 3.3.8
    - Typogrify: 1.1.18
    - Webhooks: 2.3.2

**Comment by joshuabaker** [comment]
I’m closing this as we’ve not encountered it again.

**Comment by weotch** [comment]
I also am experiencing this:

- Craft Pro 3.6.13
- Webhooks 2.3.3

![image](https://user-images.githubusercontent.com/77567/121063137-c92c6700-c77a-11eb-9784-7a8534648ef8.png)

![Image 2021-06-07 at 10 28 08 AM](https://user-images.githubusercontent.com/77567/121063388-14df1080-c77b-11eb-913b-fc06695491ac.jpg)

**Comment by carlcs** [comment]
We’re also running into this. Now trying with a dynamic debounce key `{{ now|date('i') }}` instead of `deploy`, which we’ve had before.

**Comment by brandonkelly** [comment]
Webhooks 2.4 is out now, which adds a new “Send now” button for pending webhook requests, beside their status in the request details view.

It also fixes an exception that occurred when initially attempting to send the request, if a connection with the server couldn’t be established, which would result in the job getting marked as failed, but leave the request stuck in its pending state – which is possibly how you’re ending up with so many pending requests to begin with.

**Comment by weotch** [comment]
That "Send now" button helps, but it's not an optimal solution IMO because it requires someone to notice that the webhook failed.

I'd _love_ auto-retry or auto-clear functionality for stuck webhook invocations.

**Comment by davidhellmann** [comment]
Running into the same issue. All pending :/

**Comment by howells** [comment]
I'd love a way to retry all pending web hooks. I have about 1000 that are pending for some reason.

**Comment by howells** [comment]
@brandonkelly wondered if there could be any update to this? I've tried making my own command to re-try all pending requests but I'm really struggling

**Comment by kaspar-allenbach** [comment]
Any update on this? Everything remains on pending forever. Also there is no `Send Now` button anywhere

Craft CMS: `5.8.17`
Webhook Plugin: `3.1.1`

<img width="550" height="700" alt="Image" src="https://github.com/user-attachments/assets/e15c4e89-8575-484c-b291-0312290153d0" />

**Comment by kaspar-allenbach** [comment]
Im on Webhooks Plugin 3.1.1. Where is the `Send now` Button? I can't see it anywhere 

<img width="1671" height="1407" alt="Image" src="https://github.com/user-attachments/assets/83569974-9379-49cc-8ccb-2473fc1a0946" />
