### ISSUE TITLE
'Couldn’t install plugin.' when I attempt to install the plugin on our server.

### ISSUE THREAD

**Issue by kruncher** [craftcms/webhooks#46]
### Description

The following error appears when attempting to install this plugin from the plugin store:

![image](https://user-images.githubusercontent.com/554215/125917553-adc08cca-9469-4e02-8b70-5990d90af64a.png)

Does this plugin require any additional PHP extensions that are not compiled into php:7.2-fpm?

### Steps to reproduce

1. Navigate to the plugin store.
2. Install the plugin.

### Additional info

- Craft version: 3.7.2
- PHP version: 7.2.34
- Database driver & version: MySQL 5.6.51
- Plugins & versions:
  * Google Cloud Storage | 1.4.0
  * Redactor 2.8.7

**Comment by kruncher** [comment]
After having inspected the logs it seems that the plugin failed to install/enable because the webhooks tables already existed within the database. I dropped these tables manually and then tried again and it worked.

**Comment by brandonkelly** [comment]
Thanks for pointing that out! Just released Webhooks 2.4.0 which defends against that possibility.
