### ISSUE TITLE
Body of webhook is too big for Netlify

### ISSUE THREAD

**Issue by dsteinel** [craftcms/webhooks#5]
Hello!

The webhook is sending a lot of user related datas as well as the information about the saved entry. 
Netlify's build system cannot handle hooks over about 60 kilobytes, so the build fails with an error `11:37:46 PM: System Error`. 
If I remove all datas it works like a charm. Unfortunately I am only able to remove all datas within my fork but I can not make it work with additional datas (Extra Event Attributes, Extra Sender Attributes, Extra User Attributes). It would be great to have all datas as optional parameter since some services only need a trigger without any data.

I will keep trying to create a PR ;) !

**Comment by brandonkelly** [comment]
The Custom Payload feature coming in the next release (#3) will solve this.
