### ISSUE TITLE
FR: Conditional Webhook

### ISSUE THREAD

**Issue by theskyfloor** [craftcms/webhooks#6]
Would it be possible to add a conditional field? Such as if key = value then fire web hook? Would make it easier to assign a web hook to a certain criteria. This plug-in rocks, thanks for offering it!

**Comment by brandonkelly** [comment]
It’s possible to add a condition on Zapier’s end:

<img width="1354" alt="Screen Shot 2019-03-18 at 5 02 31 PM" src="https://user-images.githubusercontent.com/47792/54571375-a518bb80-499f-11e9-81bf-f35f700759b8.png">

For now that’s our recommended solution. Eventually a version of that will be possible within Craft, but by that point this plugin won’t be needed anymore ;)

**Comment by theskyfloor** [comment]
Totally. Fair enough, I am already filtering on the Zap. Now I am intrigued as I am sure you can imagine : ) I am mainly using this with Freeform and every form submission fires 6 webhooks so far (more to come as we add more forms no doubt)... which feels excessive even with filtering on Zapier. Anyway not necessarily trying to convince you to reverse your decision just noticed how many events fire per submission thanks to the awesome new activity log!
