### ISSUE TITLE
Unexpected "spaceless" tag (expecting closing tag for the "if" tag defined near line 7).

### ISSUE THREAD

**Issue by olsp** [craftcms/webhooks#71]
### Description

When trying to access the activity, this error appears "Unexpected "spaceless" tag (expecting closing tag for the "if" tag defined near line 7)." The path is vendor/craftcms/webhooks/src/templates/_activity/macros.html
Spaceless was removed from Craft, "apply spaceless" needs to be used instead.

### Steps to reproduce

1. Install the plugin
2. Add a webhook
3. Click "Activity" in the CP under Webhooks

### Additional info

- Craft version: 4.0.2
- Webhooks Plugin: 3.0.1

**Comment by angrybrad** [comment]
Thanks! Just released 3.0.2 with a fix for this.
