### ISSUE TITLE
Cannot clear Pending Activity after cancel the craft queue

### ISSUE THREAD

**Issue by dande-sun** [craftcms/webhooks#93]
### Description
Cannot clear Pending Activity after cancel the craft queue

### Steps to reproduce

1. Cancel all the craft queue when activity is pending.
2. Click the Clear in Activity page.

### Additional info

- Craft version: Craft Pro 4.8.6
- PHP version: 8.1.25
- Database driver & version: PostgreSQL 15.6
- Plugins & versions: Webhooks | 3.1.0

**Comment by i-just** [comment]
Hi, thanks for getting in touch! That’s the expected behaviour. The control panel > Webhooks > Activity > Clear button is supposed to [clear only the jobs that are marked in the database as done](https://github.com/craftcms/webhooks/blob/3.x/src/controllers/ActivityController.php#L64).
